name: PTLogger
description: Logs playtime.
author: Genhis
website: http://genhis.6f.sk/
depend: [GLib]
softdepend: [Essentials, VanishNoPacket]
main: sk.genhis.ptlogger.PTLogger
version: ${project.version}
api-version: 1.13
